<a href="https://colab.research.google.com/github/SANTINHOS051/teste/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(1)

1


In [ ]:
w1, w2, w3 = 0.3, 0.2, 0.5

print(w1)
print(w2)
print(w3)


0.3
0.2
0.5


In [ ]:
#dados climaticos regiao A
regiaoA_temp = 22
regiaoA_chuva = 67
regiaoA_umid = 65

#eplicab=ndo modelo
regiaoA_goiaba = regiaoA_temp * w1 + regiaoA_chuva * w2 + regiaoA_umid * w3
print('Na regiao A a produçao de {} toneladas por hectare'.format(regiaoA_goiaba))

Na regiao A a produçao de 52.5 toneladas por hectare


In [ ]:

RegiaoA = [22, 67, 65]
RegiaoB = [24, 88, 95]
RegiaoC = [17, 134, 50]
RegiaoD = [18, 96, 70]
#representar o numero de pesos ultilizados na formula como uma lista
pesos = [w1, w2, w3]

In [ ]:
def teste (a,b):
  print(a+b)

In [ ]:
teste(100, 98)

198


In [ ]:
nomes = ['alice', 'bob', 'charlie']
idades = [25, 30, 35]

# Combinando listas usando zip
lista_combinada = list(zip(nomes, idades))
print(lista_combinada)
#saida: [('alice', 25), ('bob', 30), ('carlie', 35)]

[('alice', 25), ('bob', 30), ('charlie', 35)]


In [ ]:
def producao_goiaba(regiao, pesos):
  result = 0
  for x, w in zip(regiao, pesos):
    result += x * w
  return result


In [ ]:
print(producao_goiaba(RegiaoA, pesos))

52.5


In [ ]:
print(producao_goiaba(RegiaoB, pesos))

72.3


In [ ]:
import numpy as np

RegiaoA = np.array([22, 67, 65])

print(type(RegiaoA))

pesos = np.array([w1, w2, w3])

print(type(pesos))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
reg_a = np.dot(RegiaoA, pesos)
print('Regiao A: {}'.format(reg_a))

Regiao A: 52.5


In [ ]:
#exemplo

#Lista em Python
arr1 = list(range(2000000))
arr2 = list(range(1000000, 3000000))

# Vetor em numpy
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
  result += x1*x2
print(result)

4666663666667000000
CPU times: user 361 ms, sys: 0 ns, total: 361 ms
Wall time: 361 ms


In [ ]:
dados_climaticos =np.array([ [22, 67, 65],
                            [24, 88, 95],
                            [17, 134, 50],
                             [18, 96, 70], ])

print(dados_climaticos)

[[ 22  67  65]
 [ 24  88  95]
 [ 17 134  50]
 [ 18  96  70]]


In [ ]:
print(pesos.dtype)
print('-------')
print(dados_climaticos.dtype)



float64
-------
int64


In [ ]:
np.matmul(dados_climaticos, pesos)

array([52.5, 72.3, 56.9, 59.6])

In [ ]:
dados_climaticos @ pesos

array([52.5, 72.3, 56.9, 59.6])

In [3]:
import numpy as np


In [8]:
goiaba_csv = np.genfromtxt('/content/goiaba.csv', delimiter=',')

In [9]:
goiaba_csv

array([[23., 29., 95.],
       [24., 20., 21.],
       [18., 23., 16.],
       [19., 30., 36.]])

In [10]:
pesos = np.array([0.4, 0.2, 0.9])

In [12]:
rendimento = goiaba_csv @ pesos

In [14]:
resultado = np.concatenate((goiaba_csv, rendimento.reshape(4, 1)), axis=1)

In [15]:
resultado

array([[ 23. ,  29. ,  95. , 100.5],
       [ 24. ,  20. ,  21. ,  32.5],
       [ 18. ,  23. ,  16. ,  26.2],
       [ 19. ,  30. ,  36. ,  46. ]])

In [23]:
#agora é so salvar
np.savetxt('goiaba_resultado.csv',
           resultado,
           fmt='%.2f',
           delimiter=',',
           header= 'temperatura,precipitaçao,umidade,rendimento',
           comments='')